### ISSUE TITLE
LWT functionality

### ISSUE THREAD

**Issue by madebytinker** [krasnoukhov/homeassistant-smart-maic#12]
Missing LWT functionality in MQTT. With power loss of the meter HA still uses the last valid data it has received. 
BR André

**Comment by krasnoukhov** [comment]
I'm not sure what you mean and what do you expect of integration to do. Can you elaborate more please? Thanks

**Comment by madebytinker** [comment]
Hi, the problem I'm having is, that if the power supply to the meter is diconnected the homeassistant is stuck on the last received data values. As far as I understood no LWT message was agreed between client and broker and therefore with a connection loss HA does not know what to do. I propose that the LWT message should include to set all data to 0 because if no voltage is on the meter that will be the correct data.

**Comment by krasnoukhov** [comment]
Ok, I see what you mean. Do you care to come up with a PR for this?

**Comment by madebytinker** [comment]
According to what I found out the client has to publish from itself at the first MQTT discovery his last will to the broker. So in case of disconnect the broker will publish this values.

**Comment by krasnoukhov** [comment]
Ok, I see. Well, in this case client means the device that publishes the metrics? In that case I don't have control over that since that stuff comes from manufacturer's firmware

**Comment by madebytinker** [comment]
Ok, understood now that the integration has nothing to do with the MQTT data from the device itself. Will write to the smartmaic guys so that they are aware ot the problem.
Thanks for your support
