### ISSUE TITLE
ADC missing in D105

### ISSUE THREAD

**Issue by choseecz** [krasnoukhov/homeassistant-smart-maic#16]
The output data from D105 is missing the value from the ADC.

**Comment by krasnoukhov** [comment]
Thanks for the report, feel free to submit a PR with changes to support whatever's missing and I'll review and merge

**Comment by alexxs73** [comment]
I'll join the topic, please make an analog input, it's really needed for the water pressure sensor. Thank you.

**Comment by choseecz** [comment]
I'm sorry, but I don't know how to do it, I'm just a user.

**Comment by krasnoukhov** [comment]
Ok, I can see from [this payload](https://github.com/krasnoukhov/homeassistant-smart-maic/issues/11#issuecomment-2058597482) that ADC is a numeric value... Can any of you send me a screenshot of how it looks like in the web interface? @choseecz @alexxs73

**Comment by alexxs73** [comment]
Добрый день,живу в Днепре,если есть  желание можем продолжить  общение без
гугл пепеводчика)),по теме-могу дать доступ через   anydesk показать
вебморду.

чт, 5 сент. 2024 г., 11:35 Dmitry Krasnoukhov ***@***.***>:

**Comment by alexxs73** [comment]
Набирал на ходу с телефона с ощибкамм((.

чт, 5 сент. 2024 г., 11:58 Александр Сорокин ***@***.***>:

**Comment by krasnoukhov** [comment]
I don't speak russian. I just need a screenshot to understand how to call it properly and so I can add support

**Comment by alexxs73** [comment]
Ok sorry 
![5388582943452159473](https://github.com/user-attachments/assets/d3ba46fd-3000-4f71-a089-a51449750825)
![5388582943452159474](https://github.com/user-attachments/assets/959cf8bd-baf1-4f0c-bc7d-aaeeea7edc9b)

**Comment by choseecz** [comment]
<img width="1639" alt="MAIC" src="https://github.com/user-attachments/assets/ce6685f1-3c86-4974-8b67-b81d419f6d4a">

**Comment by alexxs73** [comment]
Ok
![Uploading 20240905_124312.jpg…]()

**Comment by alexxs73** [comment]
![20240905_124312](https://github.com/user-attachments/assets/106e38d0-1b0e-428a-a455-e25b1ec2c1f6)

**Comment by alexxs73** [comment]
![20240905_125116](https://github.com/user-attachments/assets/d6ce72ba-075b-4107-8705-38943ca80c9d)

minute

**Comment by krasnoukhov** [comment]
Ok please try 1.4.1 and let me know how it goes

**Comment by alexxs73** [comment]
Thank you very much, everything works.
