### ISSUE TITLE
Missing entities in D103 G3

### ISSUE THREAD

**Issue by choseecz** [krasnoukhov/homeassistant-smart-maic#18]
I have a total of three D103 G3 devices integrated.
One has 31 entities and the other two only 26 entities.
Two devices are missing "total" entities.
- total consumption
- total current
- total power
- total return
- total return power
What could be the reason for this? How to add remaining entities?

**Comment by krasnoukhov** [comment]
The logic of this integration is quite simple - it adds entities for the keys in the MQTT payload. If there's no key the entity is not added

I'd suggest checking the MQTT payload of every device. You can use MQTT explorer for that, just connect to your broker and look for the devices there, see if you can spot any difference

Feel free to post your findings here

**Comment by choseecz** [comment]
First of all, I want to apologize for the delay.
I have compared all three D103 G3 units using MQTT Explorer and the result is that they are all identical (they have the same number of keys = 30).
In HA, two units have 26 entities and only one has 31 entities. Additional entities are: total consumption / total current / total power / total return / total return power. None of these entities are transmitted directly from the D103 G3 by any key in MQTT.

**Comment by choseecz** [comment]
Yes, you are right. Two devices have A1 = 0 (only work intermittently). It would be better to check V1 as the voltage is present at all times.

**Comment by krasnoukhov** [comment]
Should be fixed now, please confirm

**Comment by choseecz** [comment]
Excellent, thank you very much.
