### ISSUE TITLE
Dry Relay switch reports unknown error but works

### ISSUE THREAD

**Issue by dolzhanskiyoa** [krasnoukhov/homeassistant-smart-maic#27]
Не працює перемикач сухого реле
При натисканні - Failed to perform the action switch Unknown Error
Але при цьому перемикання відбувається.
![image](https://github.com/user-attachments/assets/01543df8-9396-409b-9555-f259ea5af2a9)

**Comment by krasnoukhov** [comment]
Так, знаю про цю проблему, думаю можливо є сенс переробити на управління через MQTT замість того, як зараз, через API

Якщо є бажання - спробуйте, відкрийте PR
